"""fixed delete school

Revision ID: 1cf61b4c2673
Revises: 18a09986677b
Create Date: 2026-06-10 23:28:33.143811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf61b4c2673'
down_revision = '18a09986677b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('invoices_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoices_student_id_fkey'), 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
