"""added a new file <report_card_extras.py> to keep tables containing hm and class teacher signatures ,comments and report overrides data.We also added comments column on the studentmark table

Revision ID: 4679e8f9cf5f
Revises: f706abe6141b
Create Date: 2026-07-14 15:18:11.233092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679e8f9cf5f'
down_revision = 'f706abe6141b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_card_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=10), nullable=False),
    sa.Column('attendance_present', sa.Integer(), nullable=True),
    sa.Column('attendance_total', sa.Integer(), nullable=True),
    sa.Column('class_teacher_comment', sa.Text(), nullable=True),
    sa.Column('headteacher_comment', sa.Text(), nullable=True),
    sa.Column('class_teacher_initials', sa.String(length=20), nullable=True),
    sa.Column('headteacher_initials', sa.String(length=20), nullable=True),
    sa.Column('subject_initials', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'term_id', 'exam_type', name='uq_report_card_override_identity')
    )
    with op.batch_alter_table('report_card_override', schema=None) as batch_op:
        batch_op.create_index('ix_report_card_override_lookup', ['school_id', 'student_id', 'term_id', 'exam_type'], unique=False)

    op.create_table('headteacher_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=120), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('report_comment_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_comment_bank', schema=None) as batch_op:
        batch_op.create_index('ix_report_comment_bank_lookup', ['school_id', 'comment_type'], unique=False)

    op.create_table('class_teacher_signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('teacher_name', sa.String(length=120), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_id')
    )
    with op.batch_alter_table('class_teacher_signature', schema=None) as batch_op:
        batch_op.create_index('ix_class_teacher_signature_school', ['school_id'], unique=False)

    with op.batch_alter_table('student_marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_marks', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('class_teacher_signature', schema=None) as batch_op:
        batch_op.drop_index('ix_class_teacher_signature_school')

    op.drop_table('class_teacher_signature')
    with op.batch_alter_table('report_comment_bank', schema=None) as batch_op:
        batch_op.drop_index('ix_report_comment_bank_lookup')

    op.drop_table('report_comment_bank')
    op.drop_table('headteacher_signature')
    with op.batch_alter_table('report_card_override', schema=None) as batch_op:
        batch_op.drop_index('ix_report_card_override_lookup')

    op.drop_table('report_card_override')
    # ### end Alembic commands ###
