"""photo_url in the students table now returns the relative path plus the bunny cdn url through the help of properties on the talbe,same applies to documents,guardian urls etc

Revision ID: 6223c84422dd
Revises: a439dcdf7205
Create Date: 2026-07-27 12:00:49.617613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6223c84422dd'
down_revision = 'a439dcdf7205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_activity_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_activity_comments', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
