"""added nurseryactivity and studentactivity comment tables

Revision ID: a439dcdf7205
Revises: 4679e8f9cf5f
Create Date: 2026-07-15 16:24:37.403386

"""
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a439dcdf7205'
down_revision = '4679e8f9cf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursery_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_nursery_activity_school_name')
    )
    with op.batch_alter_table('nursery_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nursery_activities_school_id'), ['school_id'], unique=False)

    op.create_table('student_activity_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
   sa.Column('comment', sa.Text(), nullable=True),
sa.Column(
    'exam_type',
    postgresql.ENUM(
        'BOT',
        'MID',
        'EOT',
        name='assessmenttype',
        create_type=False
    ),
    nullable=False
),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['nursery_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'student_id', 'term_id', 'exam_type', name='uq_activity_comment_student_term_exam')
    )
    with op.batch_alter_table('student_activity_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_activity_comments_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activity_comments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activity_comments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_activity_comments_term_id'), ['term_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_activity_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_activity_comments_term_id'))
        batch_op.drop_index(batch_op.f('ix_student_activity_comments_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_activity_comments_school_id'))
        batch_op.drop_index(batch_op.f('ix_student_activity_comments_activity_id'))

    op.drop_table('student_activity_comments')
    with op.batch_alter_table('nursery_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nursery_activities_school_id'))

    op.drop_table('nursery_activities')
    # ### end Alembic commands ###
