"""add unique constraint on subjects table

Revision ID: a6a236ed8cba
Revises: 1cf61b4c2673
Create Date: 2026-07-09 00:42:02.569515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a236ed8cba'
down_revision = '1cf61b4c2673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subject_school_name_level', ['school_id', 'name', 'level'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subject_school_name_level', type_='unique')

    # ### end Alembic commands ###
